### ISSUE TITLE
slop 2.4.0 problems

### ISSUE THREAD

**Issue by banister** [leejarvis/slop#40]
Hi,

In previous versions of slop (i only tried 2.2.0 and earlier) the code i'm about to paste worked fine - that is `gist -i 1` did not raise an exception. Since i updated to 2.4.0 however I keep getting an exception, i paste the situation below:

It seems that the value of `opts[:i]` is always nil. 

Note, it's also `nil` if i pass in a real `Range` or I leave off a paramter altogether (to rely on the default):

```
[4] (pry) main: 0> gist -i 1..1
NoMethodError: undefined method `>=' for nil:NilClass
from /Users/john/ruby/projects/pry/lib/pry/helpers/command_helpers.rb:254:in `absolute_index_number'
[5] (pry) main: 0> gist -i 
NoMethodError: undefined method `>=' for nil:NilClass
from /Users/john/ruby/projects/pry/lib/pry/helpers/command_helpers.rb:254:in `absolute_index_number'
[6] (pry) main: 0> 
```

```

Fetching: slop-2.4.0.gem (100%)
Successfully installed slop-2.4.0
Gems updated: slop
crow:pry john$ rake pry
(in /Users/john/ruby/projects/pry)
/Users/john/ruby/projects/pry/Rakefile:21: warning: Insecure world writable dir /Applications/MacPorts/Emacs.app/Contents in PATH, mode 040777
[1] (pry) main: 0> def hello
[1] (pry) main: 0*   puts "hi"
[1] (pry) main: 0* end  
=> nil
[2] (pry) main: 0> gist -i 1
NoMethodError: undefined method `>=' for nil:NilClass
from /Users/john/ruby/projects/pry/lib/pry/helpers/command_helpers.rb:254:in `absolute_index_number'
[3] (pry) main: 0> show-command gist

From: /Users/john/ruby/projects/pry/lib/pry/default_commands/documentation.rb @ line 58:
Number of lines: 56

command "gist", "Gist a method or expression history to github. Type `gist --help` for more info.", :requires_gem => "gist", :shellwords => false do |*args|
  require 'gist'

  target = target()

  opts = parse_options!(args) do |opt|
    opt.banner unindent <<-USAGE
      Usage: gist [OPTIONS] [METH]
      Gist method (doc or source) or input expression to github.
      Ensure the `gist` gem is properly working before use. http://github.com/defunkt/gist for instructions.
      e.g: gist -m my_method
      e.g: gist -d my_method
      e.g: gist -i 1..10
    USAGE

    opt.on :d, :doc, "Gist a method's documentation.", true
    opt.on :m, :method, "Gist a method's source.", true
    opt.on :p, :public, "Create a public gist (default: false)", :default => false
    opt.on :i, :in, "Gist entries from Pry's input expression history. Takes an index or range.", :optional => true, :as => Range, :default => -5..-1
  end

  type_map = { :ruby => "rb", :c => "c", :plain => "plain" }
  if opts.present?(:in)
    code_type = :ruby
    content = ""
    normalized_range = absolute_index_range(opts[:i], _pry_.input_array.length)
    input_items = _pry_.input_array[normalized_range] || []

    input_items.each_with_index.map do |code, index|
      corrected_index = index + normalized_range.first
      if code && code != ""
        content << code
        content << "#{comment_expression_result_for_gist(_pry_.output_array[corrected_index].pretty_inspect)}" if code !~ /;\Z/
      end
    end
  elsif opts.present?(:doc)
    meth = get_method_or_raise(opts[:d], target, {})
    content = meth.doc
    code_type = meth.source_type

    text.no_color do
      content = process_comment_markup(content, code_type)
    end
    code_type = :plain
  elsif opts.present?(:method)
    meth = get_method_or_raise(opts[:m], target, {})
    content = meth.source
    code_type = meth.source_type
  end

  link = Gist.write([:extension => ".#{type_map[code_type]}",
                     :input => content],
                    !opts[:p])

  output.puts "Gist created at #{link}"
end
```
